apiVersion: v1
kind: Service
metadata:
  name: power-converter-ops-center-service
  namespace: default
  labels:
    app: power-converter-ops-center
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: power-converter-ops-center
